// app/components/RealAccessibilityService.ts
// This service loads REAL accessibility issues from JSON files generated by n8n + axe-core

export interface AxeNode {
  html: string;
  target: string[];
  failureSummary: string;
}

export interface AxeIssue {
  id: string;
  impact: 'critical' | 'serious' | 'moderate' | 'minor';
  description: string;
  help: string;
  helpUrl: string;
  tags: string[];
  nodes: AxeNode[];
}

export interface AccessibilityReport {
  url: string;
  timestamp: string;
  scannedBy: string;
  issues: AxeIssue[];
  summary: {
    critical: number;
    serious: number;
    moderate: number;
    minor: number;
  };
}

export interface ConvertedIssue {
  type: 'error' | 'warning';
  code: string;
  message: string;
  wcagPrinciple: string;
  selector: string;
  codeSnippet: string;
  recommendation: string;
  impact?: string;
  helpUrl?: string;
}

/**
 * Load accessibility report from JSON file
 */
export async function loadAccessibilityReport(
  pageUrl: string
): Promise<AccessibilityReport | null> {
  try {
    // Convert URL to filename
    const filename = urlToFilename(pageUrl);
    
    console.log(`🔍 Looking for report: /reports/${filename}.json`);
    
    const response = await fetch(`/reports/${filename}.json`);
    
    if (!response.ok) {
      console.log(`⚠️ No report found for: ${pageUrl}`);
      return null;
    }
    
    const report: AccessibilityReport = await response.json();
    console.log(`✅ Loaded report with ${report.issues.length} issues`);
    return report;
  } catch (error) {
    console.error(`❌ Error loading accessibility report:`, error);
    return null;
  }
}

/**
 * Convert axe-core issues to dashboard format
 */
export function convertAxeIssuesToDashboardFormat(
  axeIssues: AxeIssue[]
): ConvertedIssue[] {
  const converted: ConvertedIssue[] = [];
  
  for (const issue of axeIssues) {
    // For each node (element) that has this issue
    for (const node of issue.nodes) {
      converted.push({
        type: issue.impact === 'critical' || issue.impact === 'serious' ? 'error' : 'warning',
        code: issue.id,
        message: issue.description,
        wcagPrinciple: extractWCAGPrinciple(issue.tags),
        selector: node.target.join(' > '),
        codeSnippet: node.html,
        recommendation: node.failureSummary || issue.help,
        impact: issue.impact,
        helpUrl: issue.helpUrl,
      });
    }
  }
  
  return converted;
}

/**
 * Extract WCAG principle from tags
 */
function extractWCAGPrinciple(tags: string[]): string {
  // Check for specific WCAG guidelines
  for (const tag of tags) {
    if (tag.includes('wcag2')) {
      // Perceivable (1.x.x)
      if (tag.match(/wcag1[0-9]{2}/)) return 'Perceivable';
      // Operable (2.x.x)
      if (tag.match(/wcag2[0-9]{2}/)) return 'Operable';
      // Understandable (3.x.x)
      if (tag.match(/wcag3[0-9]{2}/)) return 'Understandable';
      // Robust (4.x.x)
      if (tag.match(/wcag4[0-9]{2}/)) return 'Robust';
    }
  }
  
  // Fallback to category-based detection
  if (tags.includes('cat.color') || tags.includes('cat.text-alternatives')) {
    return 'Perceivable';
  }
  if (tags.includes('cat.keyboard') || tags.includes('cat.navigation')) {
    return 'Operable';
  }
  if (tags.includes('cat.forms') || tags.includes('cat.language')) {
    return 'Understandable';
  }
  if (tags.includes('cat.parsing') || tags.includes('cat.name-role-value')) {
    return 'Robust';
  }
  
  return 'WCAG 2.1';
}

/**
 * Convert URL to filename
 */
function urlToFilename(url: string): string {
  try {
    const urlObj = new URL(url);
    
    // Get domain without www
    const domain = urlObj.hostname.replace('www.', '').replace(/\./g, '-');
    
    // Get path
    let path = urlObj.pathname.replace(/^\/|\/$/g, '');
    
    if (!path || path === '') {
      path = 'home';
    }
    
    // Convert to safe filename
    const pathPart = path
      .replace(/\//g, '-')
      .replace(/[^a-z0-9-]/gi, '')
      .toLowerCase();
    
    return `${domain}-${pathPart}`;
  } catch {
    return 'unknown-page';
  }
}

/**
 * Check if a report exists for a given URL
 */
export async function hasAccessibilityReport(pageUrl: string): Promise<boolean> {
  const report = await loadAccessibilityReport(pageUrl);
  return report !== null;
}